Created control layer
ianloops/credit-api-spring-kotlin pull request #2
Opened 2023-10-16 23:19 UTC by ianloops

2023-10-17 00:40 UTC, thierryaraujo requested changes

2023-10-17 00:40 UTC, thierryaraujo commented on src/main/kotlin/com/api/ianloops/credit/aplication/controller/CustomerResource.kt
Cê pode configurar um contexto no application.yml indicando o contexto da api, inclusive referenciando qual a versão:
server:
  servlet:
    context-path: /api/v1

Evita ter que repetir nos @RequestMapping e ajuda na manutenção posteriormente

2023-10-17 00:40 UTC, thierryaraujo commented on src/main/kotlin/com/api/ianloops/credit/aplication/controller/CreditResource.kt
Cê pode configurar um contexto no application.yml indicando o contexto da api, inclusive referenciando qual a versão:
server:
  servlet:
    context-path: /api/v1

Evita ter que repetir nos @RequestMapping e ajuda na manutenção posteriormente

2023-10-17 19:58 UTC, ianloops commented on src/main/kotlin/com/api/ianloops/credit/aplication/controller/CustomerResource.kt
Atualizado context-path

2023-10-17 19:58 UTC, ianloops commented on src/main/kotlin/com/api/ianloops/credit/aplication/controller/CreditResource.kt
Atualizado context-path

2023-10-19 19:08 UTC, thierryaraujo approved these changes

2023-10-19 19:41 UTC, merged